name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Publish
        run: dotnet publish src/WindowsDefenderPerformanceTool -c Release

      - name: Publish WindowsDefenderCpuTime
        run: dotnet publish src/WindowsDefenderCpuTime -c Release

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            src/WindowsDefenderPerformanceTool/bin/Release/net48/publish/WindowsDefenderPerformanceTool.exe
            src/WindowsDefenderCpuTime/bin/Release/net48/publish/WindowsDefenderCpuTime.exe
          fail_on_unmatched_files: true
